//adds everything for web
addUpEverything 
= string(global.roomBeforePrevious) + "," 
+ string(global.moneyCount) + "," 
+ string(global.moneySuffix) + ","
+ string(global.moneyCountMillion) + ","
+ string(global.moneyCountBillion) + ","
+ string(global.moneyCountTrillion) + ","
+ string(global.healthCount) + ","
+ string(global.healthCountMax) + ","
+ string(global.healthInceaseRate) + ","
+ string(global.staminaCount) + ","
+ string(global.staminaCountMax) + ","
+ string(global.staminaInceaseRate) + ","
+ string(global.attackDamage) + ","
+ string(global.defenceProtection) + ","
+ string(global.skillPointsRemaining) + ","
 
+ string(global.currentCity) + ","

+ string(global.showStatusBar) + ","
+ string(global.hitmenTimer) + ","
+ string(global.resolutionSizeText) + ","
+ string(global.trophySetInterval) + ","
+ string(global.trophyPopupDelay) + ","
+ string(global.themeType) + ","
+ string(global.fpsMode) + ","
+ string(global.rLevel) + ","
+ string(global.gLevel) + ","
+ string(global.bLevel) + ","
+ string(global.spriteTinting) + ","
                               
+ string(global.gameCompletion) + ","
+ string(global.moneyEarned) + ","
+ string(global.jobsCompleted) + ","
+ string(global.hitmenKilled) + ","
+ string(global.timesInHospital) + ","
+ string(global.tripsTaken) + ","
+ string(global.skillPointsEarned) + ","
                    
+ string(global.newYorkCompletion) + ","
+ string(global.chicagoCompletion) + ","
+ string(global.londonCompletion) + ","
+ string(global.lasVegasCompletion) + ","
                    
+ string(global.currentPlayerLevel) + ","
+ string(global.currentXP) + ","
+ string(global.currentXPNeededToLevelUp) + ","
                                        
+ string(global.jobOneBarNewYork) + ","
+ string(global.jobTwoBarNewYork) + ","
+ string(global.jobThreeBarNewYork) + ","
+ string(global.jobFourBarNewYork) + ","
+ string(global.jobFiveBarNewYork) + ","
+ string(global.jobSixBarNewYork) + ","
+ string(global.jobSevenBarNewYork) + ","
+ string(global.jobEightBarNewYork) + ","
+ string(global.jobNineBarNewYork) + ","
+ string(global.jobTenBarNewYork) + ","
                    
+ string(global.jobOneBarRankNewYork) + ","
+ string(global.jobTwoBarRankNewYork) + ","
+ string(global.jobThreeBarRankNewYork) + ","
+ string(global.jobFourBarRankNewYork) + ","
+ string(global.jobFiveBarRankNewYork) + ","
+ string(global.jobSixBarRankNewYork) + ","
+ string(global.jobSevenBarRankNewYork) + ","
+ string(global.jobEightBarRankNewYork) + ","
+ string(global.jobNineBarRankNewYork) + ","
+ string(global.jobTenBarRankNewYork) + ","
                    
+ string(global.jobOneBarChicago) + ","
+ string(global.jobTwoBarChicago) + ","
+ string(global.jobThreeBarChicago) + ","
+ string(global.jobFourBarChicago) + ","
+ string(global.jobFiveBarChicago) + ","
+ string(global.jobSixBarChicago) + ","
+ string(global.jobSevenBarChicago) + ","
+ string(global.jobEightBarChicago) + ","
+ string(global.jobNineBarChicago) + ","
+ string(global.jobTenBarChicago) + ","
                    
+ string(global.jobOneBarRankChicago) + ","
+ string(global.jobTwoBarRankChicago) + ","
+ string(global.jobThreeBarRankChicago) + ","
+ string(global.jobFourBarRankChicago) + ","
+ string(global.jobFiveBarRankChicago) + ","
+ string(global.jobSixBarRankChicago) + ","
+ string(global.jobSevenBarRankChicago) + ","
+ string(global.jobEightBarRankChicago) + ","
+ string(global.jobNineBarRankChicago) + ","
+ string(global.jobTenBarRankChicago) + ","
                    
+ string(global.jobOneBarLondon) + ","
+ string(global.jobTwoBarLondon) + ","
+ string(global.jobThreeBarLondon) + ","
+ string(global.jobFourBarLondon) + ","
+ string(global.jobFiveBarLondon) + ","
+ string(global.jobSixBarLondon) + ","
+ string(global.jobSevenBarLondon) + ","
+ string(global.jobEightBarLondon) + ","
+ string(global.jobNineBarLondon) + ","
+ string(global.jobTenBarLondon) + ","
                    
+ string(global.jobOneBarRankLondon) + ","
+ string(global.jobTwoBarRankLondon) + ","
+ string(global.jobThreeBarRankLondon) + ","
+ string(global.jobFourBarRankLondon) + ","
+ string(global.jobFiveBarRankLondon) + ","
+ string(global.jobSixBarRankLondon) + ","
+ string(global.jobSevenBarRankLondon) + ","
+ string(global.jobEightBarRankLondon) + ","
+ string(global.jobNineBarRankLondon) + ","
+ string(global.jobTenBarRankLondon) + ","
                    
+ string(global.jobOneBarLasVegas) + ","
+ string(global.jobTwoBarLasVegas) + ","
+ string(global.jobThreeBarLasVegas) + ","
+ string(global.jobFourBarLasVegas) + ","
+ string(global.jobFiveBarLasVegas) + ","
+ string(global.jobSixBarLasVegas) + ","
+ string(global.jobSevenBarLasVegas) + ","
+ string(global.jobEightBarLasVegas) + ","
+ string(global.jobNineBarLasVegas) + ","
+ string(global.jobTenBarLasVegas) + ","
                    
+ string(global.jobOneBarRankLasVegas) + ","
+ string(global.jobTwoBarRankLasVegas) + ","
+ string(global.jobThreeBarRankLasVegas) + ","
+ string(global.jobFourBarRankLasVegas) + ","
+ string(global.jobFiveBarRankLasVegas) + ","
+ string(global.jobSixBarRankLasVegas) + ","
+ string(global.jobSevenBarRankLasVegas) + ","
+ string(global.jobEightBarRankLasVegas) + ","
+ string(global.jobNineBarRankLasVegas) + ","
+ string(global.jobTenBarRankLasVegas) + ","
                    
+ string(global.propertiesOwner) + ","
+ string(global.propertiesLastEntry) + ","
+ string(global.totalPropertiesIncome) + ","
                    
+ string(global.totalPropertiesIncomeMillion) + ","
+ string(global.totalPropertiesIncomeBillion) + ","
+ string(global.totalPropertiesIncomeTrillion) + ","
+ string(global.totalPropertiesIncomeSuffix) + ","
                    
+ string(global.propertiesUninspiringGarageQuantityOwned) + ","
+ string(global.propertiesArchaicDinerQuantityOwned) + ","
+ string(global.propertiesTaxiDepotQuantityOwned) + ","
+ string(global.propertiesChinaShopQuantityOwned) + ","
+ string(global.propertiesMiaNightClubQuantityOwned) + ","
+ string(global.propertiesKenjiCasinoQuantityOwned) + ","
+ string(global.propertiesHighriseBuildingQuantityOwned) + ","
+ string(global.propertiesGrandCabaretClubQuantityOwned) + ","
+ string(global.propertiesDecadePenthouseQuantityOwned) + ","
 
+ string(global.blackmarketProperty1QuantityOwned) + ","
+ string(global.blackmarketProperty2QuantityOwned) + ","
+ string(global.blackmarketProperty3QuantityOwned) + ","
+ string(global.blackmarketProperty4QuantityOwned) + ","
+ string(global.blackmarketProperty5QuantityOwned) + ","
+ string(global.blackmarketProperty6QuantityOwned) + ","
+ string(global.blackmarketProperty7QuantityOwned) + ","
+ string(global.blackmarketProperty8QuantityOwned) + ","
+ string(global.blackmarketProperty9QuantityOwned) + ","
+ string(global.blackmarketProperty10QuantityOwned) + ","
+ string(global.blackmarketProperty11QuantityOwned) + ","
+ string(global.blackmarketProperty12QuantityOwned) + ","
+ string(global.blackmarketProperty13QuantityOwned) + ","
                   
+ string(global.qtePerformed) + ","
                    
+ string(global.slotPrice) + ","
+ string(global.clanParts) + ","
+ string(global.tripsStorageMaximum) + ","
+ string(global.agencyLevelHub) + ","
+ string(global.agencyLevelHubPoints) + ","
                    
+ string(global.slot1Status) + ","
+ string(global.slot1AgentFee) + ","
+ string(global.slot1AgentLevel) + ","
+ string(global.slot1AgentHappy) + ","
+ string(global.slot1AgentEff) + ","
+ string(global.slot1AgentLootOdds) + ","
                    
+ string(global.slot2Status) + ","
+ string(global.slot2AgentFee) + ","
+ string(global.slot2AgentLevel) + ","
+ string(global.slot2AgentHappy) + ","
+ string(global.slot2AgentEff) + ","
+ string(global.slot2AgentLootOdds) + ","
                    
+ string(global.slot3Status) + ","
+ string(global.slot3AgentFee) + ","
+ string(global.slot3AgentLevel) + ","
+ string(global.slot3AgentHappy) + ","
+ string(global.slot3AgentEff) + ","
+ string(global.slot3AgentLootOdds) + ","
                    
+ string(global.slot4Status) + ","
+ string(global.slot4AgentFee) + ","
+ string(global.slot4AgentLevel) + ","
+ string(global.slot4AgentHappy) + ","
+ string(global.slot4AgentEff) + ","
+ string(global.slot4AgentLootOdds) + ","
                    
+ string(global.slot5Status) + ","
+ string(global.slot5AgentFee) + ","
+ string(global.slot5AgentLevel) + ","
+ string(global.slot5AgentHappy) + ","
+ string(global.slot5AgentEff) + ","
+ string(global.slot5AgentLootOdds) + ","
                    
+ string(global.slot6Status) + ","
+ string(global.slot6AgentFee) + ","
+ string(global.slot6AgentLevel) + ","
+ string(global.slot6AgentHappy) + ","
+ string(global.slot6AgentEff) + ","
+ string(global.slot6AgentLootOdds) + ","
                    
+ string(global.slot7Status) + ","
+ string(global.slot7AgentFee) + ","
+ string(global.slot7AgentLevel) + ","
+ string(global.slot7AgentHappy) + ","
+ string(global.slot7AgentEff) + ","
+ string(global.slot7AgentLootOdds) + ","
                    
+ string(global.slot8Status) + ","
+ string(global.slot8AgentFee) + ","
+ string(global.slot8AgentLevel) + ","
+ string(global.slot8AgentHappy) + ","
+ string(global.slot8AgentEff) + ","
+ string(global.slot8AgentLootOdds) + ","
                    
+ string(global.slot9Status) + ","
+ string(global.slot9AgentFee) + ","
+ string(global.slot9AgentLevel) + ","
+ string(global.slot9AgentHappy) + ","
+ string(global.slot9AgentEff) + ","
+ string(global.slot9AgentLootOdds) + ","
                    
+ string(global.slot10Status) + ","
+ string(global.slot10AgentFee) + ","
+ string(global.slot10AgentLevel) + ","
+ string(global.slot10AgentHappy) + ","
+ string(global.slot10AgentEff) + ","
+ string(global.slot10AgentLootOdds) + ","
                    
+ string(global.slot11Status) + ","
+ string(global.slot11AgentFee) + ","
+ string(global.slot11AgentLevel) + ","
+ string(global.slot11AgentHappy) + ","
+ string(global.slot11AgentEff) + ","
+ string(global.slot11AgentLootOdds) + ","
                    
+ string(global.slot12Status) + ","
+ string(global.slot12AgentFee) + ","
+ string(global.slot12AgentLevel) + ","
+ string(global.slot12AgentHappy) + ","
+ string(global.slot12AgentEff) + ","
+ string(global.slot12AgentLootOdds) + ","
                    
+ string(global.slot13Status) + ","
+ string(global.slot13AgentFee) + ","
+ string(global.slot13AgentLevel) + ","
+ string(global.slot13AgentHappy) + ","
+ string(global.slot13AgentEff) + ","
+ string(global.slot13AgentLootOdds) + ","
                    
+ string(global.slot14Status) + ","
+ string(global.slot14AgentFee) + ","
+ string(global.slot14AgentLevel) + ","
+ string(global.slot14AgentHappy) + ","
+ string(global.slot14AgentEff) + ","
+ string(global.slot14AgentLootOdds) + ","
                    
+ string(global.slot15Status) + ","
+ string(global.slot15AgentFee) + ","
+ string(global.slot15AgentLevel) + ","
+ string(global.slot15AgentHappy) + ","
+ string(global.slot15AgentEff) + ","
+ string(global.slot15AgentLootOdds) + ","
                    
+ string(global.slot16Status) + ","
+ string(global.slot16AgentFee) + ","
+ string(global.slot16AgentLevel) + ","
+ string(global.slot16AgentHappy) + ","
+ string(global.slot16AgentEff) + ","
+ string(global.slot16AgentLootOdds) + ","
                    
+ string(global.slot17Status) + ","
+ string(global.slot17AgentFee) + ","
+ string(global.slot17AgentLevel) + ","
+ string(global.slot17AgentHappy) + ","
+ string(global.slot17AgentEff) + ","
+ string(global.slot17AgentLootOdds) + ","
                    
+ string(global.slot18Status) + ","
+ string(global.slot18AgentFee) + ","
+ string(global.slot18AgentLevel) + ","
+ string(global.slot18AgentHappy) + ","
+ string(global.slot18AgentEff) + ","
+ string(global.slot18AgentLootOdds) + ","
                    
+ string(global.amber_rock) + ","
+ string(global.basalt_rock) + ","
+ string(global.rainbow_rock) + ","
+ string(global.volcanic_rock) + ","
+ string(global.tourmaline_rock) + ","
+ string(global.obsidian_rock) + ","
+ string(global.mystery_stone) + ","
                    
+ string(global.black_metal_powder) + ","
+ string(global.silver_metal_powder) + ","
+ string(global.steel_metal_powder) + ","
+ string(global.gold_metal_powder) + ","
+ string(global.gun_powder) + ","
                    
+ string(global.iron_ingot) + ","
+ string(global.gold_ingot) + ","
+ string(global.copper_ingot) + ","
+ string(global.silver_ore) + ","
                    
+ string(global.diamond_gem) + ","
+ string(global.crystal_gem) + ","
+ string(global.emerald_gem) + ","
+ string(global.ruby_gem) + ","
+ string(global.fluorite_gem) + ","
+ string(global.pearl_gem) + ","
                    
+ string(global.bronze_gear) + ","
+ string(global.iron_gear) + ","
+ string(global.gold_gear) + ","
                    
+ string(global.high_voltage_battery) + ","
+ string(global.ic_chip) + ","
+ string(global.printed_circuit_board) + ","
+ string(global.magnet_technical) + ","
                    
+ string(global.steel) + ","
+ string(global.timber) + ","
+ string(global.glass_pane) + ","
+ string(global.spring) + ","
+ string(global.screw) + ","
+ string(global.wire) + ","
+ string(global.chain) + ","
+ string(global.lead_weight) + ","
                    
+ string(global.quality_leather) + ","
+ string(global.plastic) + ","
+ string(global.silk_cloth) + ","
+ string(global.rubber) + ","
+ string(global.linen_cloth) + ","
                    
+ string(global.ballistic_fiber) + ","
+ string(global.carbon_fiber) + ","
                    
+ string(global.magazine) + ","
+ string(global.supply_crate) + ","
                    
+ string(global.pistolBlueprint) + ","
+ string(global.pistolBlueprintFound) + ","
+ string(global.shotgunBlueprint) + ","
+ string(global.shotgunBlueprintFound) + ","
+ string(global.sniperBlueprint) + ","
+ string(global.sniperBlueprintFound) + ","
+ string(global.lmgBlueprint) + ","
+ string(global.lmgBlueprintFound) + ","
+ string(global.throwablesBlueprint) + ","
+ string(global.throwablesBlueprintFound) + ","
+ string(global.meleeBlueprint) + ","
+ string(global.meleeBlueprintFound) + ","
+ string(global.submachineBlueprint) + ","
+ string(global.submachineBlueprintFound) + ","
+ string(global.automaticBlueprint) + ","
+ string(global.automaticBlueprintFound) + ","
+ string(global.minesBlueprint)+ ","
+ string(global.minesBlueprintFound)
                    
return(addUpEverything);
